plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.cicy.mobile.code'
version = '2.3.338'

android {
  namespace 'com.cicy.mobile.code'
  defaultConfig {
    versionCode 1
    versionName '2.3.338'
  }
  packagingOptions {
    jniLibs.useLegacyPackaging = true
  }
}

dependencies {
  implementation 'androidx.core:core-ktx:1.15.0'
}
